# Generated by Django 4.1.5 on 2023-01-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='code',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
